server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #你本地的数据库用户名
    password: 21021036 #你本地的数据库密码
    url: jdbc:mysql://localhost:3306/xianbao?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: localhost
    port: 6379
    database: 4

# 配置mybatis-plus实体和xml映射
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto



# 分页
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

ip: localhost

alipay:
  appId: 9021000131685036
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwGnCYsrt/TgNPM//LJtlT1XtgS/dPneBPGvb9iKxsfEkRTV/LrBCU2gc5YLBwaW8wZk/ki4WuRkb1iAJY1bOHk0ntqg5Ig6mDRWlkvOUvTZemtDy0F+B2FwersQyAgF6GM21FZFoY2Mj2cxIlo04TcGY8nIfKHLagpors3HpWjxCvVHR8UnFA5yWKImK6V6iY/nDhx5xe67vdNvsSsH/55pb/ckMnfogOV43mcdw/3JAze1obfL7zDgu1NaKajfnF1rzP5GcFHztzC2PFLDzoPcaYQTS+bbfVKkJuq70N6pTCgZfjL1iBlqzFQJ45NASoGAG/gzEbtTBf76RcjektAgMBAAECggEBAJ87KPhJFBQl/AQPpoiQVg3hiC8oQTRyMjIU1aOlgxKMxpyoc6f7qvqMsd+Ft8PM8ca3nCGwrm1ICj1Uf5rHkA9UdJI7I7MZqZqSlpuJ2UkORcNsUT8eH81nQX5TFlTSvaVmtrT56iVxTzTYE16I7L3S8f54IqfzkoZsUE2fhdbg/DwANtqd4yAZhlps8+epv1UuLMB4ilPH/EGBT3gQsBFDHfnnqZ6mpEfpHFnrF7aPSYnlC6RG5dIESe98rSauNrIa1sHkdiciqjNeqXzAphgElzWQA0oRE/scvxT1eJQwy3l2oa2n4pVTyGNAjvLlAqSxMiI2S7cSVWykX1zde5kCgYEA+g+LoVi+6aP9NfMAURJQ2fw+k86KUZzSjUi2RJcIaRDvNZBFr98ynQ5qCqPSv1YkfGXcDALqHaBnE1XvzOGysmxWNYkuMKwBG8GeN1A7d7qX6a5TApyF0AXRotxmzZ93s4CFDYVaaU/JRN9jNwFwC6oR4pcZu6u9BVRBZbXbC9sCgYEAtEk1OIcmtS5rmxbu22/BK+nkIqbZ88+GG8xshnALI9YBMMSyO3z3Sr9y33JRWCAqSGq0+gVzIKza8yMeADegyZB/tDGA5L5Kao9jmLz0sqaf8qA7qPgcmg5dUp+HkgPmlQHMUI/9a9UkuYsNbKnb/FZaa6BER8SiZRhFME/PMZcCgYB3qPK3TeFlqnyj0VnIccxQ070aO87CyRmUVEQsRF3Y8SqW5igCxfrRXzFtUAGsX8tr385RzR88+CH7BbePwj0h1mfWjIOW9Og+4QMWEwWyAI9rWmkMqdv6tJ4hofhr0zCTrB9/Xd3q4Sw+EevHSZ/VZRfT51yACumT4EK/Kivc2wKBgCMl9qtLph9CqpX09aJwej++fMzIrMtc1S+MPkhDhdh5u4evgXQZm/jFtHadygAdXUD7FMd90oE3UgR+/zVZow5JDqypzhBKjSWTSP6ZMDe4Roy98oOxw5nBXS5jjcHI4uaAED5QpD6msl8+HeLmhs3+Y+iBuW4ohuSgw7R0iteHAoGAVDL+5O9kNC4qdcKjDSYbaEPaR5JSohhI2J6jex0MAu8JH6Ah1PeI34Fv7qqOHTGfGENNPKMiAiNJi9KB5OAg9zo3/YAS277YFrcMtQxG6QXs5/i0vxuLx9qudnL3/dBE2yjzOoNqjpBZU9qjaqVRU/1G7FYRC4YY0haspP8oJIM=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp9mIEuLiStkgRcQ8pcJ3sUambxApD1kIeyzTCUCa+phzlCtadu5Umq0xaD3/ZRVkM/U0lIanNc7nb5gVAHtL9Y1B5BcZWOQodys1wcIdoEXXHfI9NfVe0leoIWJ/Zf6p/Dky8/amvqPVLd2vTWFfxcXrIMFo5x/GVoJk92hyXUWR/mPEd3Kq3/mfm2f88oDDJYjLzCdZHHuPnrkZIWLBQw0wQFAb3yUlWK/70kvoAILbfwHBp9CcTxN6fTU4pKju3u5jphSgbg/GKD36EIZZg9odGxkH0ooj7mBz9N8P+QGeBH7DRvYD/fmE29mf3FN6DAVBWamC6dTxq6dlSWgndwIDAQAB
  notifyUrl:  http://vgj3sm.natappfree.cc/alipay/notify